#!/bin/bash

branchName=$(git branch | grep '*' | sed 's/* //' | sed 's/th-/[#/' | sed 's/-.*/]/')

if [ -z "$firstLine"  ] ;then #Check that this is not an amend by checking that the first line is empty
   sed -i -r "1s/^/$branchName /" $1
fi
